#!/usr/bin/env sh
#----------------
#  ENVCTL
#----------------
# -> Reload/logoff i3wm
# -> Reload Dunst
# -> Toggle Dunst

# :: Functions

rel_i3(){
	i3-msg exit  && dunstify -a System "i3" "Window Manager Restarted"
}

rel_dunst(){
	pkill dunst && sleep 1 && dunstify -a System -t 1500 "dunst" "Restarted"
}

tog_dunst(){
    if [ $(dunstctl is-paused) = 'true' ]; then dunstctl close-all && dunstify -a System -t 1500 -h string:x-dunst-stack-tag:dnd "dunst" "DND Disabled" && dunstctl set-paused toggle; else dunstify -a System -t 1500 -h string:x-dunst-stack-tag:dnd "dunst" "DND Enabled" && sleep 1.5 && dunstctl set-paused toggle; fi
}

# :: Main

while getopts ":idn" option; do
    case $option in
        i) rel_i3;;
        d) rel_dunst;;
        n) tog_dunst;;
        \?) exit 1;;
    esac
done
